# Generated by Django 2.1.4 on 2018-12-11 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeperApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermap',
            name='user_name',
        ),
    ]
