# Generated by Django 2.1.4 on 2018-12-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeperApp', '0002_remove_usermap_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermap',
            name='mines',
            field=models.CharField(default=[[1, 1]], max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermap',
            name='map',
            field=models.CharField(max_length=600),
        ),
    ]
