# Generated by Django 2.1.4 on 2018-12-13 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeperApp', '0003_auto_20181212_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermap',
            name='mines',
        ),
    ]
